### ISSUE TITLE
Lots of `EXPECT_TRUE` instead of `EXPECT_EQ` in tests

### ISSUE THREAD

**Issue by beryll1um** [nicro/etl#1]
Google `gtest` framework provides many different ways to do the same things. The main difference of all available calls is error messages. You can get much clearer error messages if you use `EXPECT_EQ` instead of `EXPECT_TRUE` in many places. For example: https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/tests/array_test.cpp#L7 https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/tests/list_test.cpp#L12 https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/tests/string_test.cpp#L10

**Comment by nicro** [comment]
Fixed with commit 3a19a7f22dd30fbb7c69421bcb598dab6a6abf5d.
