### ISSUE TITLE
Problem in `reinterpret_cast` usage in `memcpy`

### ISSUE THREAD

**Issue by beryll1um** [nicro/etl#3]
https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/etl/inc/string.hpp#L15 https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/etl/inc/string.hpp#L16 Hey dude! I hope you know what [`reinterpret_cast`](https://en.cppreference.com/w/cpp/language/reinterpret_cast) is really usage case. You don't really need to use it in this case, because void pointer type casting to another pointer type is a legal usage case for `static_cast`. If you can use more specific and safe variant, do it!

**Comment by nicro** [comment]
Fixed with commit 3a19a7f22dd30fbb7c69421bcb598dab6a6abf5d.
