### ISSUE TITLE
Cannot call `etl::list::empty`

### ISSUE THREAD

**Issue by beryll1um** [nicro/etl#4]
https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/etl/inc/list.hpp#L293-L295 Your `empty` method include initializing a non-const iterator object that implements an interface to modify const class values. Just use the `cbegin` and `cend` methods to fix it.

**Comment by nicro** [comment]
Fixed with commit 3a19a7f22dd30fbb7c69421bcb598dab6a6abf5d.
